name: PR Preview

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install
      - name: Build Quartz
        run: npx quartz build
      - name: Deploy PR Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_PREVIEW }}
          publish_dir: ./public
          destination_dir: pr-preview/pr-${{ github.event.pull_request.number }}